### PR TITLE
chore: Apply google-java-format to all files for consistency

### PR DESCRIPTION
**Pull request by aababilov**
See https://github.com/google/google-java-format.

$ google-java-format -i $(find . -name '*java')

### CODE REVIEW

**Review by barbeau — APPROVED** [review]
Thanks @aababilov! 👍

**Comment by aababilov** [comment]
Sean, you have effectively reverted [my change](https://github.com/MobilityData/gtfs-validator/commit/dcbe2f33371a319ed1d7e0df7565e769928ffa46) in `GtfsAnnotationProcessor.java`. You have removed those lines:

```
     for (TypeElement type : typesIn(annotatedElementsIn(roundEnv, GtfsEnumValues.class))) {	
          enumDescriptors.add(analyser.analyzeGtfsEnumType(type));	
     }
```

Please may I ask you to not resolve merge conflicts in my pull requests to prevent similar situations in future?

**Comment by barbeau** [comment]
@aababilov Sure - apologies, I was trying to speed up the process. In the future I'll wait for you to resolve conflicts.

**Comment by aababilov** [comment]
No worries, Sean! I know that you wanted to save my time.

Merge conflicts are evil! Let the pull request authors deal with them ;)

**Pull request merged**
