### PR TITLE
feat: Move gtfsvalidator.cli package into new cli sub-module. 

### PR DESCRIPTION
**Pull request by bdferris-v2**
**Summary:**

Per discussion in #1188, I'm proposing to move the `gtfsvalidator.cli` package and associated classes for the GTFS Validator command-line interface into their own Gradle sub-module.  This will support future modularization and packaging of the validator in ways that don't assume a CLI.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues

### CODE REVIEW

**Review by maximearmstrong — APPROVED** [review]
LGTM! Thanks a lot @bdferris-v2

**Review by maximearmstrong — APPROVED** [review]
LGTM! Thanks a lot @bdferris-v2

**Review by maximearmstrong — CHANGES_REQUESTED** [review]
I just tested the behavior locally, and it seems that the JAR file works, but the validators are not invoked.

This is stdout when using the JAR file built on the `master` branch:
Capture d’écran, le 2022-08-08 à 18 21 05
Capture d’écran, le 2022-08-08 à 18 22 24

and now the stdout with the new JAR file:
Capture d’écran, le 2022-08-08 à 18 20 44

Also, comparing the reports indicates a problem. Using `master`:
Capture d’écran, le 2022-08-08 à 18 32 52

using the new one:
Capture d’écran, le 2022-08-08 à 18 32 24

**Comment by bdferris-v2** [comment]
@maximearmstrong indeed that's a subtle bug.  When shadowJar minimization moved from `main` to `cli`, it caused the dynamically-loaded validators in `main` to be dropped since shadowJar is minimizing dependencies (which `main` now is).  I added an exclude to fix this.

Regarding acceptance tests, maybe we can add an issue to track fixing that as well?

**Comment by maximearmstrong** [comment]
All good. I tested it locally and it worked well. Thanks for this modification @bdferris-v2

Regarding acceptance tests, I've opened #1232. I think we could add a few new rules. Your thoughts are welcome :)

**Review by maximearmstrong — APPROVED** [review]

**Pull request merged**
