### PR TITLE
feat: Include agency_id in routes.txt (warning) when 1 agency

### PR DESCRIPTION
**Pull request by KClough**
**Summary:**

#878 

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by isabelle-dr** [comment]
Hello @KClough, thank you for this contribution! ☀️
Is this ready for review?

**Comment by KClough** [comment]
> Hello @KClough, thank you for this contribution! ☀️ Is this ready for review?

Yes. @bdferris-v2 FYI.

**Comment by isabelle-dr** [comment]
It looks like this Best Practice was removed in https://github.com/MobilityData/GTFS_Schedule_Best-Practices/pull/44, which was intended to remove parts of the Best Practices that were already being covered by the spec. 
That being said, I can't find any mention of this in the spec...

**Comment by bdferris-v2** [comment]
I missed @isabelle-dr comment here, but added a [comment](https://github.com/MobilityData/gtfs-validator/issues/878#issuecomment-1293800960) in issue #878 asking about the same thing.

**Comment by isabelle-dr** [comment]
This means that for this validator notice, we are missing the reference documentation to point the validator users to (just like the reference to feed_info.txt Best Practices in [missing_recommended_field](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#missing_recommended_field)).
I posted a message on the Best Practice PR to propose adding it back because it looks like it was removed by mistake.
If people agree, I propose we first add it back to the Best Practices before merging this PR.

**Comment by isabelle-dr** [comment]
closing #1318 is replacing this PR

**Pull request closed without merging**
