### PR TITLE
ci: Automatically format code

### PR DESCRIPTION
**Pull request by barbeau**
**Summary:**

This PR applies the GitHub Action https://github.com/axel-op/googlejavaformat-action on all pull requests and pushes to master branch, which will check the format of the code according to https://github.com/google/google-java-format and if it's not formatted correctly with push a commit to automatically format it.

**Expected behavior:** 

GitHub Action will check the code format, and if it's not formatted will push a commit to format it.

Closes https://github.com/MobilityData/gtfs-validator/issues/615

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: -new feature short description-" (PR title must follow the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/))
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by barbeau** [comment]
Hmmm, looks like the commit to apply formatting changes is failing with:

```
...
validator/processor/src/main/java/org/mobilitydata/gtfsvalidator/processor/TableLoaderGenerator.java
Committing changes
  /usr/bin/git commit --all -m Google Java Format
  [detached HEAD 681a617] Google Java Format
   2 files changed, 18 insertions(+), 20 deletions(-)
  /usr/bin/git push
  fatal: You are not currently on a branch.
  To push the history leading to the current (detached HEAD)
  state now, use
  
      git push origin HEAD:<name-of-remote-branch>
  
Error: The command 'git' failed with exit code 128
```

**Comment by barbeau** [comment]
Issue opened on the GitHub Actions repo here:
https://github.com/axel-op/googlejavaformat-action/issues/11

**Comment by barbeau** [comment]
@lionel-nj This is ready for review now. You can see the code that was auto-formatted in this PR in https://github.com/MobilityData/gtfs-validator/pull/616/commits/99ea2f6a188d2654bacb0fabb4b7a739961d31b6 as a result of the action.

Based on the comments in https://github.com/axel-op/googlejavaformat-action/issues/11 I'm not yet sure if this will commit on PRs with branches from other user repositories, but if that fails we can reconfigure it at that time to commit on merges("push") to master only. I'd prefer to keep it in PRs if possible so it's squashed as part of the PR and we don't clutter the main branch with formatting commits.

**Review by lionel-nj — APPROVED** [review]
Thanks @barbeau! This will really help us having standardized format.

**Comment by lionel-nj** [comment]
> Based on the comments in axel-op/googlejavaformat-action#11 I'm not yet sure if this will commit on PRs with branches from other user repositories, but if that fails we can reconfigure it at that time to commit on merges("push") to master only. I'd prefer to keep it in PRs if possible so it's squashed as part of the PR and we don't clutter the main branch with formatting commits.

We can always try with one of our forks and see https://github.com/lionel-nj/gtfs-validator

**Pull request merged**
