### PR TITLE
feat: Refactor web validator error handling

### LINKED ISSUE #1419: Web Validator: Refactor error handling
### Describe the problem

The original implementation relies on the Google Cloud Pub Sub's automatic retry functionality. This worked well when we were debugging out of memory issues, and needed to increase the infrastructure capacity to handle larger files.

However, after reviewing some production errors, some issues like large GTFS files or unexpected exceptions will retry multiple times despite the fact that the same result will occur.

In order to provide better UX, we can store any unhandled exception message and update the web client to pass this information to the user. 

### Proposed solution

In order to accomplish this, I propose the following changes:

- Update the service logic to always write a job json file, currently it is only used if there is a countryCode or url supplied
- Update the service logic so that we store processing status to the job json file
- Update the service error handling logic to write an error status + message to the job json file
- Update the service error handling logic to respond with 2xx message to prevent retries
- Update the client to poll for the job json file + status complete rather than the report file
- Update the client to show the error message when the job json reports an error status

### Alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KClough**
**Summary:**

Resolves #1419 

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by KClough** [comment]
Marking as draft until [this PR is merged](https://github.com/MobilityData/gtfs-validator/pull/1415) and potentially add additional unit tests to cover this new functionality.

**Comment by briandonahue** [comment]
@KClough I updated the `JobMetaData` to have more explicit chained constructors rather than some generated and some explicit, and I fixed some tests that broke related to your and my changes around JobMetadata.

Some validation controller tests are still failing related to my question above about returning a 202 ACCEPTED instead of a 500 SERVER ERROR on error conditions...

**Review by briandonahue — CHANGES_REQUESTED** [review]

**Comment by davidgamez** [comment]
Let's resume this work when #1487 is completed to be able to test on staging.

cc: @isabelle-dr @KClough

**Comment by davidgamez** [comment]
This issue had been addressed by #1688 and #1689

**Pull request closed without merging**
