### PR TITLE
feat: Move notice subclasses inside the corresponding validators

### PR DESCRIPTION
**Pull request by aababilov**
Each notice from `main` is produced by a single validator.
Here we limit visibility of notice subclass better.

### CODE REVIEW

**Comment by barbeau** [comment]
@aababilov Good idea! This is cleaner and makes it easier to explain how to contribute a new validation rule too (as it's all in one place). Could you refactor the remaining notices too so all changes are in the same PR?

**Comment by lionel-nj** [comment]
That looks generally good to me! As @barbeau said it makes it easier to implement new rule (as a newcomer): everything related to a validation rule would be self-contained.

**Comment by aababilov** [comment]
I am glad that you like that!

IDEA makes refactoring easy with drag-and-drop, so here is the full migration.

**Review by lionel-nj — APPROVED** [review]
🚀 LGTM ! Thanks a lot @aababilov.

**Pull request merged**
