### PR TITLE
feat: Update Notice source code such that field name comments match documentation in RULES.md

### PR DESCRIPTION
**Pull request by bdferris-v2**
As part of our effort to alignment documentation and source code in #1324, this PR applies an automated transform to update the comments of each Notice field in source to match the equivalent field documentation string from `RULES.md`.  This gets us one step closer to generating `RULES.md` from source code directly.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues

### CODE REVIEW

**Comment by bdferris-v2** [comment]
@isabelle-dr I know this review looks a little bit scary, but it's largely an automated transformation from RULES.md to source code.  As always, curious what you think.

**Comment by briandonahue** [comment]
@bdferris-v2 in looking at this for #1289 I noticed some copy/paste mistakes where row number comment was copied for file name field, so I fixed those.

**Comment by bdferris-v2** [comment]
@briandonahue those are actually errors in the source `RULES.md` file :)  But fixing them here is appreciated, thanks!

**Review by isabelle-dr — APPROVED** [review]
Hey @bdferris-v2, sorry for the late answer, and thank you for this first step in the direction of a programmatically generated doc! 
This LGTM. 
We should keep in mind that as we work on this, all new `...Notice.java` and `...Validator.java` files that add new notices will need to include this syntax.

**Comment by isabelle-dr** [comment]
After the conflicts are resolved, I think we're good to merge this PR! 
cc @davidgamez

**Pull request merged**
