### PR TITLE
Implement #237 - Implement Zone ID presence verification 

### PR DESCRIPTION
**Pull request by lionel-nj**
**Summary:**

`stops.zone_id` is conditionally required. If `fare_rules.txt` is provided, then is it required for all types of stops except `STATION` and `ENTRANCE`

**Expected behavior:** 

A `MissingRequiredValueNotice` should be generated and added to the result repo each time the aforementioned condition is not respected.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "Fix #<issue_number> - <short description of fix and changes>" (for example - "Fix #1111 - Check for null value before using field")
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by fabrice-v** [comment]
@lionel-nj What is the status of this PR?

**Comment by e-lo** [comment]
Why was this closed – Is this no longer a valid rule that needs enforcing?

**Comment by fabrice-v** [comment]
The status of this PR was unclear. The associated issue #237 is still opened.

**Comment by lionel-nj** [comment]
@fabrice-v it was in-progress but we had to switch to other tasks. Looking at it, it seems like a few improvements could be done before code review. We should add the PR to the board so that we can plan work for the next sprint.

**Comment by fabrice-v** [comment]
PR don't go to the board, only issues. Make sure the associated issue is in the right column. We will reopen when resuming work.

**Pull request closed without merging**
