### PR TITLE
Implement #441 - Implement info notice

### PR DESCRIPTION
**Pull request by lionel-nj**
**Summary:**

This PR provides support to implement a new type of notice that will give information about the validation process inside the validation report.

**Expected behavior:** 

Notice should be generated and added to `ValidationResultRepo` when `GenerateInfoNotice` is called
Capture d’écran, le 2020-10-22 à 12 45 52

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "Fix #<issue_number> - <short description of fix and changes>" (for example - "Fix #1111 - Check for null value before using field")
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by lionel-nj** [comment]
@fabrice-v  I would like us to take some time to discuss and see why some tests ar failing during our next meeting please :)

**Comment by fabrice-v** [comment]
Not ready for review, tests are failing
https://github.com/MobilityData/gtfs-validator/pull/443/checks?check_run_id=1294381351

**Comment by fabrice-v** [comment]
> @fabrice-v I would like us to take some time to discuss about the failing tests during our next meeting please :)

And yes ok :)

**Review by fabrice-v — APPROVED** [review]
lgtm

**Pull request merged**
