### PR TITLE
chore: Use FluentLogger instead of stderr and stdout

### PR DESCRIPTION
**Pull request by aababilov**
FluentLogger is more flexible and professional than stdout and stderr.

Note that Main.java keeps printing to stdout because its information
should be visible to the user on screen.

### CODE REVIEW

**Comment by barbeau** [comment]
Still need to click "Update branch" here to merge master, presumably because this PR was opened before I changed the GitHub setting...

**Review by barbeau — APPROVED** [review]
Thanks @aababilov!

**Comment by f8full** [comment]
> the GitHub setting...

What setting? :)

**Comment by f8full** [comment]
Got it https://github.com/MobilityData/gtfs-validator/pull/589#issuecomment-758813234

**Pull request merged**
