### PR TITLE
fix: Update acceptance_test.yml to reflect new -cli.jar naming.

### LINKED ISSUE #1139: Refactor handling of project version numbers and tags
Per discussion in https://github.com/MobilityData/gtfs-validator/pull/1125#discussion_r869435195, we'd like to consider a few potential changes to how `gtfs-validator` handles version numbers.  Two potential issues:

*  The use of a leading `v` in the version tag (ala v3.1.0) causes problems for some tooling (Java Modules, Mac OS app packaging) that expects numeric major.minor.patch version numbers.
* Our use of a `versionTag` environment variable for passing in version information is maybe not idiomatic Gradle?  My limited research has suggested that overriding `project.version` via a command-line flag ala `-Pversion=1.2.3` is a more consistent way of setting the project version for the entire build.

### PR DESCRIPTION
**Pull request by bdferris-v2**
**Summary:**

As part of issue #1139, PR #1147 changed how shadow jar artifacts are named.  We updated that naming in all GitHub workflows except for one place in `acceptance_test.yml` where it continued to reference the jar produced on the `master` branch with the old naming scheme.  Now that PR #1147 is in on the `master` branch, we can resolve the TODO there to reference the new jar naming scheme.

Closes #1139.

- [X] Run the unit tests with `gradle test` to make sure you didn't break anything
- [X] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [X] Linked all relevant issues

### CODE REVIEW

**Review by barbeau — APPROVED** [review]
Thanks @bdferris-v2!

**Comment by barbeau** [comment]
Oh, just realized this is still marked as "draft". Was it ready for review?

**Comment by bdferris-v2** [comment]
@barbeau I was just waiting to see if the Acceptance Test actually ran successfully before flipping over for review.  It looks like it's working!

@maximearmstrong or @isabelle-dr any chance you could review?  I think Acceptance Test will continue to fail until we get this in.

**Review by maximearmstrong — APPROVED** [review]
LGTM! Thank you @bdferris-v2

**Pull request merged**
