### PR TITLE
feat: Changed Fares Transfers to Fare Transfers

### LINKED ISSUE #1871: GTFS Feature Changes
### Describe the problem

GTFS feature changes to reflect comments in https://github.com/MobilityData/gtfs-validator/pull/1812

### Proposed solution

- Change Fares Transfers to Fare Transfers
- Change Frequency-Based Service to Frequencies
- Change logic of Pathway Signs to "One signposted_as value OR one reversed_signposted_as in pathways.txt"
- URL changes for Frequencies and Fare Transfers as reflected in https://github.com/MobilityData/gtfs-validator/blob/master/docs/FEATURES.md

### Alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qcdyx**
**Summary:**
Closes #1871 
I found that we are missing the logic of Pathway Connections, so I added loadPathwayConnectionsFeature method in FeedMetadata.
As per requirement of changes of the url, I found that #1877 already made the changes. @emmambd 

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Add or update any needed [documentation](https://github.com/MobilityData/gtfs-validator/tree/master/docs) to the repo 
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by emmambd** [comment]
Hey @qcdyx! I can't QA this yet because the test package document action fails, but some things to clarify: 

- The Pathway Connections feature isn't new - it's a name change for Pathways basic. 
- The requirement isn't to add URLs from scratch - it's that there are 2 old URLs that will "break" when a user clicks on them because they have the wrong names. The Frequencies URL needs to change https://gtfs.org/getting_started/features/base_add-ons/#frequencies and the Fare Transfers URL needs to change: https://gtfs.org/getting_started/features/fares/#fare-transfers

**Comment by emmambd** [comment]
Looks great on the QA side! All links work, I tested to see that Pathway Signs still triggers when only 1 of the necessary fields is added. Ready to go.

**Comment by qcdyx** [comment]
@emmambd  thanks for your clarification.

**Comment by jcpitre** [comment]
I don't see tests for `Pathway Details` and `Pathway Signs`. Should there be?

**Review by jcpitre — APPROVED** [review]
LGTM

**Review by davidgamez — APPROVED** [review]
LGTM

**Pull request merged**
