### PR TITLE
feat: flex - added `forbidden_same_day_booking_field_value` notice

### PR DESCRIPTION
**Pull request by cka-y**
**Summary**

This PR introduces a new validation rule that triggers an `ERROR` severity notice when the following conditions are met:

- `booking_type = 1` (Same-day booking)
- Any of the following fields are present in the booking rule:
  - `prior_notice_last_day`
  - `prior_notice_last_time`
  - `prior_notice_start_time`
  - `prior_notice_service_id`

**Expected Behavior**

A validation notice will be generated if the conditions listed above are met, flagging the presence of restricted fields in a same-day booking rule.

Example using [this test dataset](https://github.com/user-attachments/files/17131804/Archive.zip).

Screenshot 2024-09-25 at 9 41 42 AM

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Add or update any needed [documentation](https://github.com/MobilityData/gtfs-validator/tree/master/docs) to the repo 
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by emmambd** [comment]
Yay for acceptance tests! @tzujenchanmbd After taking a look at the new error, I think [we missed an exception in the spec:](https://gtfs.org/documentation/schedule/reference/#booking_rulestxt) 

Looks like `prior_notice_start day` is only Forbidden for booking_type=1 if `prior_notice_duration_max` is defined. In the feed above, `prior_notice_duration_max` does not exist, so it should not trigger the error. 

Can you confirm before @cka-y updates the logic?

**Comment by cka-y** [comment]
seems like the logic you're mentioning @emmambd is also referenced in https://github.com/MobilityData/gtfs-validator/issues/1827

**Comment by tzujenchanmbd** [comment]
> I think the fix here is to just remove prior_notice_start_time as a forbidden field and have https://github.com/MobilityData/gtfs-validator/issues/1827 and https://github.com/MobilityData/gtfs-validator/issues/1832 manage this use case.

LGTM. It seems #1827, #1832, and #1833 can handle `prior_notice_start_time` well. We can remove it here.

Notice name, description, and columns displayed also lgtm!

**Review by qcdyx — APPROVED** [review]
LGTM

**Review by jcpitre — APPROVED** [review]

**Comment by emmambd** [comment]
Looks like this has been approved twice - just want to be explicit the logic change has to be made above to `prior_notice_start_time` as a forbidden field before this should be merged.

**Comment by cka-y** [comment]
it has now been addressed @emmambd

**Pull request merged**
