### PR TITLE
feat: Move key annotation and entity interfaces into a new `model` module

### PR DESCRIPTION
**Pull request by bdferris-v2**
This will allow us to break up some potential circular dependencies with upcoming support for notice documentation generation, as discussed in #1324 and #1361.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues

### CODE REVIEW

**Comment by bdferris-v2** [comment]
Now wondering if this should have been `core/model` instead.  I could see an argument for splitting up `core` into other submodules, such as `core/io` or `core/notices`.

**Comment by davidgamez** [comment]
> Now wondering if this should have been `core/model` instead. I could see an argument for splitting up `core` into other submodules, such as `core/io` or `core/notices`.

We can always start with this _simple_ approach(just model) and refactor in the future adding the model back to the core as `core/model` and the other core childrens.

**Comment by bdferris-v2** [comment]
Fair enough.

**Review by davidgamez — APPROVED** [review]
LGTM 🚀

**Pull request merged**
