### PR TITLE
Ensure consistency of Route entities with new extensions

### PR DESCRIPTION
**Pull request by lionel-nj**
**Summary:**

Summarize the changes in the pull request including how it relates to any issues (include the #number, or link them).

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Format the title like "Fix #<issue_number> - <short description of fix and changes>" (for example - "Fix #1111 - Check for null value before using field")
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by fabrice-v** [comment]
Iceboxed

**Comment by e-lo** [comment]
Suggestion: when you icebox something that is needed to support a specific extension, can you add a tag with extension name so that people implementing that extension can easily find them (and hopefully help implement)?

**Comment by e-lo** [comment]
Question: not sure why the branch was deleted? Is the work no longer valid?

**Comment by fabrice-v** [comment]
Then branch was deleted so future forks won't inherit stalled branches.
On GitHub, the branch can be restored in one click 
image

**Pull request closed without merging**
