### PR TITLE
HTML Report, limit records displayed

### LINKED ISSUE #1306: The HTML file doesn't work on large reports
### Describe the bug

This was flagged by a user working at a GTFS consulting company. 
It seems like when there is a high number of notices triggered, the HTML report doesn't respond well. 
The dataset attached triggers 1000 instances of `missing_timepoint_value` and 55294 instances of `equal_shape_distance_diff_coordinates`. When I try to open details on one of these two, the file is either really slow, or breaks and gives me a blank error page. 

### Steps/Code to Reproduce

- Run validator on the dataset provided.
- Open the HTML file and try to open details for the `missing_timepoint_value` notice.
- The report stops responding. 

### Expected Results

I am able to see the details of the notices.

### Actual Results

Error, blank page.

### Screenshots

_No response_

### Files used

[Westchester_County_Bee-Line_System-20220829T194048Z-e3571abf-0284-4b6d-8a3c-0a9f8dbd8d33-89455444-11e2-4cee-8d9e-7834adb84666.zip](https://github.com/MobilityData/gtfs-validator/files/10246051/Westchester_County_Bee-Line_System-20220829T194048Z-e3571abf-0284-4b6d-8a3c-0a9f8dbd8d33-89455444-11e2-4cee-8d9e-7834adb84666.zip)

### Validator version

3.1.1

### Operating system

Mac OS

### Java version

_No response_

### Additional notes

We should have an alternative when an occurrence is really high:
- the user can see the total number of times the notice is triggered, and just show 20 rows in "details" as examples, with a clear mention that this is a sample only.

### PR DESCRIPTION
**Pull request by briandonahue**
**Summary:**

Closes #1306. The HTML report is not functioning well when large amounts of records are flagged for one or more notices.  

We will limit the number of displayed records to a sample of 100, which does not cause performance errors.  The full list is still available in the JSON report.

**Expected behavior:** 

Accordion sections should still open/close and display sample records.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by briandonahue** [comment]
@isabelle-dr @davidgamez This was added onto the #1389, the metadata PR, so is marked as draft until that PR is merged. Here is an example of the message added when # of affected records > 100:
image

**Comment by isabelle-dr** [comment]
Great :)

**Comment by isabelle-dr** [comment]
@briandonahue now that #1389 is merged, this one is ready for review right?

**Comment by briandonahue** [comment]
> @briandonahue now that #1389 is merged, this one is ready for review right?

@isabelle-dr Had to fix some conflicts, it should be good now, though!

**Comment by briandonahue** [comment]
Screenshot example: 
image

**Review by davidgamez — APPROVED** [review]
LGTM!

**Comment by isabelle-dr** [comment]
Merging then :) 

Thank you @briandonahue for this contribution!

**Pull request merged**
