### PR TITLE
chore: Downgrade to Java 8

### PR DESCRIPTION
**Pull request by aababilov**
Google is still using the old Java.

The updated code was tested on OpenJDK 1.8.

### CODE REVIEW

**Review by barbeau — COMMENTED** [review]
Thanks @aababilov! Could you also change the *.yml files in `.github/workflows` where JDK 1.11 is referenced to use JDK 1.8 instead?

This will make sure the build and tests pass in the CI environment on Java 8 as well.

**Comment by aababilov** [comment]
> Thanks @aababilov! Could you also change the *.yml files in `.github/workflows` where JDK 1.11 is referenced to use JDK 1.8 instead?

Sure, done!

**Review by barbeau — APPROVED** [review]
LGTM, thanks @aababilov!

**Comment by aababilov** [comment]
Thanks for review!

**Pull request merged**
