### PR TITLE
feat: added `forbidden_prior_day_booking_field_value`, `invalid_prior_notice_duration_min` and `forbidden_prior_notice_start_day` notices

### PR DESCRIPTION
**Pull request by cka-y**
**Summary:**

This PR introduces three new validation notices: `forbidden_prior_day_booking_field_value`, `invalid_prior_notice_duration_min`, and `forbidden_prior_notice_start_day`.

- **forbidden_prior_day_booking_field_value**:
  - **Error Logic**: 
    - Trigger when `booking_type = 2` and either `prior_notice_duration_min` or `prior_notice_duration_max` is present.

- **invalid_prior_notice_duration_min**:
  - **Error Logic**: 
    - Trigger when `prior_notice_duration_min` is greater than `prior_notice_duration_max`.

- **forbidden_prior_notice_start_day**:
  - **Error Logic**: 
    - Trigger when `prior_notice_start_day` is defined and `prior_notice_duration_max` is also defined.

**Expected Behavior:**

A validation notice with ERROR severity is generated when any of the above conditions are met for each specific notice.

Using [this modified feed](https://github.com/user-attachments/files/17213398/Archive.zip), the following validation results were obtained:  
Screenshot 2024-10-02 at 11 18 38 AM

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Add or update any needed [documentation](https://github.com/MobilityData/gtfs-validator/tree/master/docs) to the repo 
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by emmambd** [comment]
@cka-y On a QA side, works as expected!

**Comment by emmambd** [comment]
@cka-y For `forbidden_prior_notice_start_day`, I just realized the "invalid value" language might be confusing, since the field itself is forbidden in cases where `prior_notice_duration_max is provided`, not just that there's an invalid specific inputted value for it. 

Suggested change: `prior_notice_start_day` is forbidden when `prior_notice_duration_max` is set"

**Review by qcdyx — APPROVED** [review]
LGTM

**Comment by cka-y** [comment]
done @emmambd -- waiting for @tzujenchanmbd approval before merging

**Comment by tzujenchanmbd** [comment]
LGTM on columns displayed, notice names, and description.

**Review by tzujenchanmbd — APPROVED** [review]

**Pull request merged**
