### PR TITLE
feat: Apply multiple @PrimaryKey annotations to Transfers 

### LINKED ISSUE #1113: Update validator after the addition of primary and foreign keys in the specification
> UPDATE: This issue has been updated after [PR # 326](https://github.com/google/transit/pull/326) has been merged in the spec in June 2022.

In Q4 2021, the definition of primary and foreign keys was added to GTFS in [PR #278](https://github.com/google/transit/pull/278).
This validator already defines primary and foreign keys, and this informs the following notices:
- [ForeignKeyViolationNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#ForeignKeyViolationNotice)
- [DuplicateKeyNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#DuplicateKeyNotice)
- [TranslationFOreignKeyViolationNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#TranslationForeignKeyViolationNotice)

A comparison[ has been made](https://github.com/MobilityData/gtfs-validator/issues/1079#issuecomment-1068180857) between the existing primary & foreign key implementations in the specification and the validator. From this comparison, we should update the validator with:
1. in `calendar_dates.txt`, add `service_id` and `date` as the primary key
2. in `frequencies.txt`, add `trip_id` and `start_time` as the primary key
3. in `transfers.txt`, add `from_stop_id`, `to_stop_id`, `from_trip_id`, `to_trip_id`, `from_route_id`, `to_route_id`as the primary key
4. in `translations.txt`, ~~add that all records are a primary key, or add an additional rule similar to [DuplicateFareRuleZoneIdFieldsNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#duplicatefarerulezoneidfieldsnotice) to flag a duplicate row.~~ add `table_name`, `field_name`, `language`, `record_id`, `record_sub_id`, `field_value` as the primary key.

### Definition of done
- The DuplicateKeyNotice is triggered for:
  - two rows in `calendar_dates.txt` that have the same values for `service_id` and `date`
  - two rows in `frequencies.txt` that have the same values for `trip_id` and `start_time`
  - two rows in `transfers.txt` that have the same values for `from_stop_id`, `to_stop_id`, `from_trip_id`, `to_trip_id`, `from_route_id`, `to_route_id`
  - ~~two duplicate rows in `translations.txt`~~ two rows in `translations.txt` that have the same values for: `table_name`, `field_name`, `language`, `record_id`, `record_sub_id`, `field_value`.

### PR DESCRIPTION
**Pull request by KClough**
**Summary:**

Summarize the changes in the pull request including how it relates to any issues (include the #number, or link them).

Resolves #1113

This PR expands @bdferris-v2  's efforts and applies the multiple @PrimaryKey functionality to the remaining schema's defined in #1113. 

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

~~Marking as draft until #1190 is merged.~~

I've tested this functionality with a hand edited GTFS data set that can be shared if helpful.

### CODE REVIEW

**Comment by bdferris-v2** [comment]
I already updated Translations in #1190.  And for transfers, you'll need to add translationRecordIdType fields to the @PrimaryKey, marking `from_stop_id` and `to_stop_id` as the RECORD_ID and RECORD_SUB_ID, respectively.  All other columns need to be marked as UNSUPPORTED.

**Comment by KClough** [comment]
> I already updated Translations in #1190. And for transfers, you'll need to add translationRecordIdType fields to the @PrimaryKey, marking `from_stop_id` and `to_stop_id` as the RECORD_ID and RECORD_SUB_ID, respectively. All other columns need to be marked as UNSUPPORTED.

Thanks @bdferris-v2 , I should've caught that. I would have assumed cherry picking my commit would have had a merge conflict with yours. I've addressed the additional requested changes for transfers.

**Review by bdferris-v2 — APPROVED** [review]
LGTM

**Comment by isabelle-dr** [comment]
I tested the 4 conditions in #1113 with a test dataset, and everything is working, thank you @KClough for this PR, and @bdferris-v2 for the updates in #1190! Merging, since the code review has been performed. 

Screen Shot 2022-08-05 at 11 58 01 AM




I used with the jar file from [this action run](https://github.com/MobilityData/gtfs-validator/actions/runs/2799593682)

**Pull request merged**
