### PR TITLE
feat: Support UK as a synonym for GB country code

### PR DESCRIPTION
**Pull request by aababilov**
ISO 3166-1 Alpha 2 country code for the United Kingdom is "GB" but feed
names use "UK" instead.

### CODE REVIEW

**Review by lionel-nj — APPROVED** [review]
Good catch, thanks @aababilov. Waiting for @barbeau's approval to merge.

**Comment by barbeau** [comment]
@aababilov Which feed names are you referring to, and where are they named? Just trying to understand why this changed is needed, if the feed name is something defined by the person inputting the feed into the validator (as opposed to part of the GTFS feed itself).

**Comment by aababilov** [comment]
All feeds for United Kingdom at Google start from the `uk-` prefix instead of `gb-`. I would like to support them out of the box.

**Comment by dbabramov** [comment]
I am wondering whether deriving the locale from the feed name is necessarily the most robust way to go about this.
That requires all consumers to name their feeds in the same way, and break in strange and obscure ways if the feed naming pattern is not complied with.
Would it be a better idea to pass the locale explicitly?

**Comment by barbeau** [comment]
>Would it be a better idea to pass the locale explicitly?

I agree with @dbabramov on this ☝️ - it's a more standardized approach. My concern with the solution in this PR is that we'll be getting all kinds of aliasing and formatting requests to support different naming conventions.

It would also be nice if we could make at least the locale (and maybe name?) parameters optional to simplify things for users. I could see needing to know the locale of feeds upfront potentially problematic for some - I opened an issue for this at https://github.com/MobilityData/gtfs-validator/issues/539.

**Comment by barbeau** [comment]
Actually, looking into this more for `uk`, it looks like ISO does recognize this officially as an alias for `gb`:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Exceptional_reservations

So we'd still be within the ISO spec for this PR implementation.

I propose we merge this PR and then separate the country code from the feed name in a new PR.

@aababilov @dbabramov thoughts?

**Comment by aababilov** [comment]
I agree to pass the country code to the validator because feed names are too Google-specific. Let's merge this PR for now to unblock me and I will prepare another one.

**Comment by barbeau** [comment]
Hmmm, I'm not sure why the CI build is failing again:

>org.mobilitydata.gtfsvalidator.cli.CliParametersAnalyzerTest > provideStorageDirectoryCliParameterWithoutSpecifyingUrlShouldReturnFalse FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at CliParametersAnalyzerTest.java:113

It passed locally for me via gradle command line and within IntelliJ.

I'm going to go ahead and merge because it's unrelated to this PR. We'll see if it passes after that and if not open an issue.

**Review by barbeau — APPROVED** [review]

**Comment by barbeau** [comment]
Huh...passes fine in the master branch 🤷:
https://github.com/MobilityData/gtfs-validator/runs/1665054412

**Pull request merged**
