### PR TITLE
feat: new booking_rules.txt validation notices

### PR DESCRIPTION
**Pull request by cka-y**
**Summary:**

This pull request enhances the `BookingRulesEntityValidator` by adding new validation checks and corresponding notices. It also updates the test cases to cover these new validations.

Added `missing_prior_notice_durantion_min`, `missing_prior_day_bokking_field_value`, `forbidden_prior_notice_start_time` and `missing_prior_notice_start_time` notices to the validator

image

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Add or update any needed [documentation](https://github.com/MobilityData/gtfs-validator/tree/master/docs) to the repo 
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Review by davidgamez — APPROVED** [review]
LGTM

**Comment by tzujenchanmbd** [comment]
@cka-y 1 question for the `missing_prior_notice_start_time` notice in the screenshot -

The notice should be triggered when there is no `prior_notice_start_time` value AND `prior_notice_start_day` value exists. It's odd that we still have a priorNoticeStartTime value `00:00:00` there?

**Comment by cka-y** [comment]
@tzujenchanmbd Great catch! The `00:00:00` value is the default for `null` `GtfsTime`. I’ve replaced `priorNoticeStartTime` with `priorNoticeStartDay` in the notice and updated the screenshot accordingly. Let me know what you think!

**Review by tzujenchanmbd — APPROVED** [review]
Thanks @cka-y ! 
LGTM on notice name, field displayed, and description.

**Pull request merged**
