### PR TITLE
feat: Add an icon for the GUI application

### LINKED ISSUE #1162: Add an icon for the GUI application
The new packaged app could benefit from an official application icon.  By default, it gets a generic Java icon when packaged, which is less than ideal.

### PR DESCRIPTION
**Pull request by bdferris-v2**
**Summary:**

Replaces the default Java icon used for the packaged application.

Screen Shot 2022-06-03 at 9 11 07 AM

Closes #1162

- [X] Run the unit tests with `gradle test` to make sure you didn't break anything
- [X] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [X] Linked all relevant issues
- [X] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by bdferris-v2** [comment]
Note that I accidentally had one commit in this PR that used my bdferris@google.com address (as opposed to bdferris-v2@google.com), so CLA Assistant is going to complain.  Sorry I missed that!

**Comment by isabelle-dr** [comment]
Thank you so much @bdferris! LGTM. If you're not planning other additions, I can merge & publish the release (🎉)

**Comment by bdferris-v2** [comment]
I've got one more tweak for the in-app icon.  Give me five minutes, almost there.

**Review by isabelle-dr — APPROVED** [review]

**Comment by isabelle-dr** [comment]
I'm surprised the `Package Application` didn't run, I thought it would be triggered on every commit?

**Comment by bdferris-v2** [comment]
@isabelle-dr it looks like it ran to me?

https://github.com/MobilityData/gtfs-validator/actions/runs/2436559851

**Comment by isabelle-dr** [comment]
Oh okay, it is `Package Installers`. It looks great!

**Comment by bdferris-v2** [comment]
@isabelle-dr the CLA Assistant is still blocking this, such that I don't think I can submit on my own.  Do you have the power to override?

**Comment by isabelle-dr** [comment]
I do :) 
Are you done on your end?

**Comment by bdferris** [comment]
Yep!  Submit away!

**Pull request merged**
