### PR TITLE
feat: Add notice descriptions to HTML report

### LINKED ISSUE #1364: Add the rule descriptions directly in the validation report.
### Describe the problem

Currently, when the users open the HTML report, it is difficult to understand what the problems are; the users need to guess from the notice name. 
Often, they don't see the link to the documentation provided in the text:
_Please find this notice description here._

### Proposed solution

We should include the descriptions directly in the validator output (JSON and interface) so that the user doesn't necessarily _need_ to go back and forth between the report and the documentation. 
We should still keep the link to the documentation, for the cases where the users want to know more (where is the spec requiring this? how do I fix this?)

This work depends on https://github.com/MobilityData/gtfs-validator/issues/1324 and all the work @bdferris is currently doing to solve this issue (#1362, #1361, #1346, #1345)

### Alternatives you've considered

_No response_

### Additional context

Current interface - no way of knowing what the problem is besides the notice name.

Screenshot 2023-03-24 at 6 11 07 PM

### PR DESCRIPTION
**Pull request by briandonahue**
**Summary:**

Closes #1364. This PR depends on #1433 being merged first, so is initially submitted as a draft PR.

Add notice descriptions for each notice to the HTML report. Converts markdown comment to HTML.

**Expected behavior:** 

Should include the specific description for each notice in the report

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

image

image

Attached are zip files output for 2 different reports. View the `report.html` in your browser after unzipping.

[alhambra.zip](https://github.com/MobilityData/gtfs-validator/files/11559304/alhambra.zip)
[westchester.zip](https://github.com/MobilityData/gtfs-validator/files/11559305/westchester.zip)

### CODE REVIEW

**Comment by briandonahue** [comment]
Took a stab at adding the column descriptions too:
image

Updated zips attached with report.html:

[alhambra.zip](https://github.com/MobilityData/gtfs-validator/files/11559578/alhambra.zip)
[westchester.zip](https://github.com/MobilityData/gtfs-validator/files/11559579/westchester.zip)

**Comment by isabelle-dr** [comment]
The column descriptions are such a nice addition :)
A quick change request related to the user experience: can we change the text "Please find this notice description here" to "You can see more about this notice here", since now the description is included in the report?

**Comment by briandonahue** [comment]
> A quick change request related to the user experience: can we change the text "Please find this notice description here" to "You can see more about this notice here", since now the description is included in the report?

@isabelle-dr done!

**Review by davidgamez — APPROVED** [review]
Nicely done!

**Pull request merged**
