### PR TITLE
feat: generate rules page from json file

### PR DESCRIPTION
**Pull request by ryon**
> Closes https://github.com/MobilityData/gtfs-validator/issues/1401

## Summary

- Generate rules page from new JSON file instead of Markdown

## Expected behavior

`rules.html` will load `rules.json`, group the rules by category, and display them in index tables, along with more details underneath, linked together with page anchor

Screenshot 2023-04-28 at 10 53 26 PM

## Notes / Questions

- Where does `rules.json` come from or "live" normally? I wrote this code using a copy provided by @KClough 
- The current JSON file is fairly incomplete as compared to the Markdown file

## Checklist

- [ ] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by themightychris** [comment]
This is going to have to wait for #1327 to land and annotate content to reach par with RULES.md

We'll also need a process for generating the JSON file as part of the GitHub workflow that builds new releases, attaching it as an extra artifact to each release.

**Review by themightychris — APPROVED** [review]
Looks good aside from the hard-coded `rules.json` and other callouts, but they could be addressed in follow-up PRs. This shouldn't merge until we have a better `rules.json` at least though.

**Comment by themightychris** [comment]
@KClough remove the latest merge commit and push up an updated `rules.json` for testing

**Comment by ryon** [comment]
## New

Updated with latest `rules.json` export from Kevin:

- `shortSummary` and `description` now both displayed
- `sectionReference` links now displayed (though there's nothing like a "label" or "title" field, so they look a little funny)
- Some reference link URLs updated since I noticed they were redirecting
- Added more anchor links to help navigate around the document
- Improved (somewhat) the mobile layout, including collapsing the big tables down into `display: block`

## Known issues

- Some `shortSummary` values seem to be simply the first n words of a fuller `description`, so neither field makes sense on its own
    - Example: `duplicate_route_name`
    - Possible diagnosis: some intermediate system is determining the shortSummary is too long, and dumping the overflow into description
- Markdown table do not always parse correctly
    - Example: `duplicate_route_name` description
    - Possible diagnosis: the tab characters `\t` seem to be the issue. If I manually replace them with spaces, the table renders. This might be a bug or limitation in marked.js, or it’s a problem with the spec
- Newline characters are not always parsed well, maybe?
    - Example: `new_line_in_value` description
    - Honestly not entirely sure what the expected output is here, because it’s describing a problem with parsing newline characters! But I suspect what we are showing might be slightly wrong
- Fields occasionally have no `description`
    - Example: `unknown_column`
    - This might be expected behavior?

## Screenshot

Including the new "Top" link and short summaries

Screenshot 2023-06-02 at 6 30 35 PM

**Comment by bdferris-v2** [comment]
Regarding `shortSummary`, that seems like a bug in the comment parsing code.  I think I can get that fixed.  Opened #1478 to track.

**Comment by isabelle-dr** [comment]
@ryon [here is the explanatory content](https://docs.google.com/document/d/1YikaHpjGTDb_Apeu6QU05LDHfeB1kYFV1aoBJsF8LxA/edit) to add at the beginning of the documentation page!

**Comment by bdferris-v2** [comment]
@ryon I believe the `shortDescription` bug should be fixed in `master` at this point.  Give it a shot and see if it helps.

Regarding your other questions:
* I can confirm that Notices will not always include a `description`.  I think this is WAI unless we want to change our documentation policy.
* Regarding `sectionReference`, I was thinking it would be reasonable to hard-code title strings for these in the page generator.
* Regarding tab characters in Markdown tables, I bet we could get rid of those if it's causing issues.

**Comment by ryon** [comment]
## New

- Added intro content
- Moved table of contents to the side in large viewports
- Created `SectionRefLink` component with hardcoded list of labels/urls for a given key, with a fallback to the older behavior if a key is not listed
- Improved handling of empty `description`s
- Misc fixes

## Remaining issue

- Removing/replacing the tabs from the markdown table in that one field description would be helpful

## Screenshots

### Intro content and new TOC layout

validator-intro-section

### Section reference links with hardcoded titles/URLs

validator-section-references

**Comment by KClough** [comment]
Closed in favor of https://github.com/MobilityData/gtfs-validator/pull/1508

**Pull request closed without merging**
