### PR TITLE
chore: Corrected typos in Features.md

### PR DESCRIPTION
**Pull request by jcpitre**
The FEATURES.md file contained `Bike Allowed` whereas the right string is `Bikes Allowance`
Other typos related to uppercase - lowercase confusion
`In-station traversal time` replaced by `Traversal Time`

### CODE REVIEW

**Review by emmambd — APPROVED** [review]
LGTM. Minor changes expected later in the quarter, but it's good for this to be an accurate reflection of the code

**Review by qcdyx — APPROVED** [review]
LGTM

**Comment by davidgamez** [comment]
@emmambd  Is this already fixed as part of the latest feature flags enhancements?

**Comment by emmambd** [comment]
@davidgamez Yes! This would override new changes. Can be closed.

**Pull request closed without merging**
