### PR TITLE
ci: Add more feeds to end-to-end GitHub workflow

### PR DESCRIPTION
**Pull request by f8full**
**Summary:**

Following the conversation in #712 , this PR extends end to end worflow as follow

- it adds 3 feeds suggested by @timMillet to the original workflow
- it adds a new workflow file named `end_to_end_100.yml` which contains 100 feeds, including the remaining ones from Tim's suggestion
- it adds a new workflow file named `end_to_end_big.yml` dedicate to feeds that need more memory than the default amount to be validated successfully.

They were taken from http://transitfeeds.com/feeds somewhat randomly as long as they didn't seem staled.  Some exceptions were made for big or original data.

**Expected behavior:** 

image

Please make sure these boxes are checked before submitting your pull request - thanks!

~~- [ ] Run the unit tests with `gradle test` to make sure you didn't break anything~~ NO CODE CHANGE
- [x] Format the title like "feat: -new feature short description-" (PR title must follow the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/))
~~- [ ] Linked all relevant issues~~
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by aababilov** [comment]
Great! The more feeds we test, the better. Thank you, Fabrice, LGTM!

**Comment by f8full** [comment]
Cool! Note that it seems the feeds don't pass validation for what looks like an out of memory error with Norway.
https://github.com/f8full/gtfs-validator/runs/1868392984?check_suite_focus=true

**Comment by f8full** [comment]
@aababilov Increasing heap size in the run command fixed the IDFM feed but it seems there is an issue with Bueno Aires even with the increased heap size. I'll comment it until I get to a 100 feed at which point I'll switch the PR status to ready and let you guys decide.

**Comment by f8full** [comment]
Workflow execution: https://github.com/f8full/gtfs-validator/runs/1876641201?check_suite_focus=true

**Comment by barbeau** [comment]
Thanks for working on this @f8full! Is this reading for review/merge?

Also, just to clarify, this PR will ensure that the validator doesn't crash on all of these feeds. However, it won't flag if we output errors on datasets that should be clean - that type of testing is being discussed in https://github.com/MobilityData/gtfs-validator/issues/734.

**Comment by f8full** [comment]
Yes @barbeau , it is ready. It doesn't analyse any reports generated so it can show crashes and feeds that take significantly longer to validate. I also split feeds that need special memory configuration.

**Comment by f8full** [comment]
An you're welcome! :)

**Review by barbeau — APPROVED** [review]
Thanks @f8full, this is great! 💯

**Comment by f8full** [comment]
Always a pleasure! :)

**Comment by f8full** [comment]
cc @e-lo @mcplanner

**Pull request merged**
