### PR TITLE
feat: Add a rule that stations (location_type 1) must be the parent_station of some stop (location_type 0).

### PR DESCRIPTION
**Pull request by bradyhunsaker**
**Summary:**

Part of #153.

The notice is of type INFO because there is nothing in the specification or best practices stating that stations should have stops. There is a discussion about changing this in #1348.

As part of the change, this renames ParentLocationTypeValidator to the more general name ParentStationValidator.

For unit testing it is now necessary to consider two types of notices, so all "contains()" calls are changed to "containsExactly()" or "containsExactlyElementsIn()" to be sure that additional notices are not ignored.

**Expected behavior:** 

If a location of type 1 (station) never appears as the parent station of a location of type 0 (stop/platform), then issue a notice.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Run the unit tests with `gradle test` to make sure you didn't break anything
- [X] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [X] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by isabelle-dr** [comment]
@bradyhunsaker is this ready to review or are you planning to put more work there? :)

**Comment by bradyhunsaker** [comment]
It was ready for review, but when I tried to sync after other changes I managed to mess up the PR. So I think I need to clean that up first. That's why I marked it as a draft a week or two ago.

I expect to get to that this weekend and will update here.

**Comment by bradyhunsaker** [comment]
I'm not sure how to repair this PR, so I'm going to delete it and create a new one with the same change (updated with the commits made to the master branch in the time since I first created this).

**Comment by bradyhunsaker** [comment]
Closing.

**Comment by bradyhunsaker** [comment]
The replacement PR is #1493.

**Pull request closed without merging**
