### PR TITLE
False positive on missing calendar_date field

### LINKED ISSUE #401: [BUG] False positive on missing calendar date field
**Describe the bug**
The validator is turning up an error claiming that entries are missing in the calendar_dates file, but that appears to be in correct.

**To Reproduce**
Run the validator on this feed: https://www.ci.manteca.ca.us/CommunityDevelopment/MantecaTransit/googletransit/google_transit.zip

**Expected behavior**
I did not expect to see an error on this file.

**Witnessed behavior**
`Notice{filename='calendar_dates.txt', level='ERROR', code='15', title='Missing required value', description='Missing value for field:`date` marked as required in entity with id:`null`', extra='{fieldName=date}'}, `

**Environment used**
- OS: macOS Catalina 10.15.6
- Java version: 11.0.5
- gtfs validator version: gtfs-validator-v1.3.0-SNAPSHOT.jar

**Additional context**
Not that Manteca's feed is not applying the agency ID correctly.

### PR DESCRIPTION
**Pull request by lionel-nj**
closes #401 

**Summary:**

This PR provides support to prevent the erroneous generation of `MissingRequiredValueNotice` when a GTFS file contains blank lines.

**Expected behavior:** 

`MalformedCsvRowNotice` should be generated and added to the validation result repo if:
- [x] a GTFS file contains blank lines (1 notice per blank line)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- ~[ ] Format the title like "Fix #<issue_number> - <short description of fix and changes>" (for example - "Fix #1111 - Check for null value before using field")~
- [x] Linked all relevant issues
- ~[ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~

### CODE REVIEW

**Comment by lionel-nj** [comment]
After analyzing the dataset provided in the linked issue, it appears that:
1. `calendar_dates.txt` might be malformed: I suspect each line of the file to miss a CRLF. Editing said file and adding a line return, allowed to get rid of the notice that were generated.

This CSV malformation should have been caught when parsing said file, not when processing the related GTFS entities.

Investigating this further.

**Comment by lionel-nj** [comment]
As discussed, we will:
- [ ] investigate possibility to setup parser to take CRLF into account
- [ ] provide a minimal fix to avoid producing `ParsedEntity` wii all rows set to `null`

**Comment by lionel-nj** [comment]
Turns out that I misunderstood the source of the problem. What actually happens is that for this particular dataset, `calendar_dates.txt` contains blank lines:
Capture d’écran, le 2020-10-30 à 13 59 54

Therefore, we should no longer investigate possibility to setup parser to take CRLF into account, but instead we should investigate the process we currently have to deal with such blank lines.

Will still provide a minimal fix to avoid producing `ParsedEntity` from blank lines of a `CSV` file.

**Comment by lionel-nj** [comment]
Looking back to our list of closed PRs, it seems that https://github.com/MobilityData/gtfs-validator/issues/402 is related to this issue.

**Comment by barbeau** [comment]
I've hit the blank line issue in both Tampa GTFS datasets I've tested (HART and USF), so I'd be in favor of treating this as a warning instead of an error.

**Comment by lionel-nj** [comment]
I am not sure that we should treat that one as a warning instead of an error. My understanding is that this type of malformation can lead to generation of other notices. Since the behavior of the validator is not guaranted after the first error, treating this one as a warning would prevent users to debug their validation report (assuming `abort_on_error` was set to `true`).

However, this is just a suggestion that is totally up for change. @fabrice-v we could discuss that during our next meeting to be sure that we are all on the same page and that I am not missing some key element.

**Comment by lionel-nj** [comment]
I understand also that the spec does not specify that CSV file should not contain blank lines, hence the treatment as warning you were suggesting @barbeau, right?

**Comment by barbeau** [comment]
>I understand also that the spec does not specify that CSV file should not contain blank lines, hence the treatment as warning you were suggesting

Correct - to my knowledge having empty lines in a CSV file isn't against any CSV or GTFS rule, especially at the end of a file. So IMHO it seems harsh to consider this a failing error. I agree that malformed rows (e.g., that don't have enough columns based on the headers) should throw errors.

> Since the behavior of the validator is not guaranted after the first error, treating this one as a warning would prevent users to debug their validation report (assuming abort_on_error was set to true).

So the validator currently stops on warnings unless abort_on_error = false?

**Comment by lionel-nj** [comment]
> So the validator currently stops on warnings unless abort_on_error = false?

The validator stops on the first error (not on the first warning) unless `abort_on_error = false`

**Comment by fabrice-v** [comment]
> > I understand also that the spec does not specify that CSV file should not contain blank lines, hence the treatment as warning you were suggesting
> 
Relevant #317 , #213 
@barbeau Do the other datasets you have seen fail the validator pass the python google one? I guess they have some special magic or something, maybe @maximearmstrong will have some time to check that at some point.

Thks for the discussion, I'm still arguing the point the validator should reject those datasets

**Review by fabrice-v — CHANGES_REQUESTED** [review]
Code hasn't been reviwed. Some issue after merging #469 

See the failing checks
image

**Comment by barbeau** [comment]
>Do the other datasets you have seen fail the validator pass the python google one?

Yes, the HART dataset passes the Python validator without any errors (see below and attached)

image

[validation-results.zip](https://github.com/MobilityData/gtfs-validator/files/5476570/validation-results.zip)

Here's the HART GTFS zip file:

[google_transit_hart.zip](https://github.com/MobilityData/gtfs-validator/files/5476579/google_transit_hart.zip)

**Comment by lionel-nj** [comment]
As discussed we relaunch jobs: https://github.com/MobilityData/gtfs-validator/runs/1343258317?check_suite_focus=true

**Review by fabrice-v — APPROVED** [review]
False alarm: CI runner had a bad network day. (Forgot to take a screen capture)
Issue rised when trying to persist the coverage report on GitHub infrastructure.

**Pull request merged**
