### PR TITLE
build: use mavenCentral() instead of jcenter()

### PR DESCRIPTION
**Pull request by ed-g**
Gradle says jcenter() has be deprecated. I've run tests before and after this change, and in both cases the `Task :output-comparator:test FAILED`, so at least there is no difference.

**Summary:**

Fixes warnings on build.

**Expected behavior:** 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
> Task :output-comparator:test FAILED

org.mobilitydata.gtfsvalidator.outputcomparator.cli.MainTest > tooManyCorruptedSource_invalidTest FAILED
    com.google.common.truth.ComparisonFailureWithFacts at MainTest.java:356

8 tests completed, 1 failed

- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by lionel-nj** [comment]
Hi @ed-g 👋🏾

Thank you for this contribution! Our team will soon review it.

**Review by lionel-nj — APPROVED** [review]
LGTM, thanks @ed-g. 

It appears that all tests are successful on the CI and on my computer, could you specify your configuration please?

**Comment by ed-g** [comment]
Hi @lionel-nj!

This is from building on linux x86, openjdk-17.

It looks like java 17 has finally dropped a function which system-lambda-1.2.0.jar depends on?

Someone suggests https://github.com/webcompere/system-stubs as an alternative.

https://github.com/stefanbirkner/system-lambda/issues/23

```
> Task :output-comparator:test FAILED
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.github.stefanbirkner.systemlambda.SystemLambda (file:/home/validate/.gradle/caches/modules-2/files-2.1/com.github.stefanbirkner/system-lambda/1.2.0/949a1f977d7287196301a6ec1ef2214e1c93981d/system-lambda-1.2.0.jar)
WARNING: Please consider reporting this to the maintainers of com.github.stefanbirkner.systemlambda.SystemLambda
WARNING: System::setSecurityManager will be removed in a future release

org.mobilitydata.gtfsvalidator.outputcomparator.cli.MainTest > tooManyCorruptedSource_invalidTest FAILED
    com.google.common.truth.ComparisonFailureWithFacts at MainTest.java:356
```

**Comment by ed-g** [comment]
I'm only superficially familiar with java testing, but I've swapped in the System Stubs library.

The tooManyCorruptedSource_invalidTest test now runs, but it does fail on an output comparison,

```
tooManyCorruptedSource_invalidTest

expected: …ources":["source-id-5","source-id-4"],"sourceIdCount":5…
but was : …ources":["source-id-4","source-id-5"],"sourceIdCount":5…
	at app//org.mobilitydata.gtfsvalidator.outputcomparator.cli.MainTest.tooManyCorruptedSource_invalidTest(MainTest.java:356)

```

I don't know if the swapped position of source-id-5 and source-id-4 is significant, if it is not, maybe this check could be changed to allow either ordering?

**Comment by ed-g** [comment]
I've updated the test to pass with either ordering of source-id-4 and source-id-5, and all tests are successful on my machine.

**Comment by lionel-nj** [comment]
Hi @ed-g, it seems that this PR contains several changes. Could you separate them to help evaluate the potential side effects please?
1. jCenter -> mavenCentral
2. library change: SystemLambda -> SytemStub
3. the changes in the `tooManyCorruptedSource_invalidTest`

Although the order in `tooManyCorruptedSource_invalidTest` is not important, IMO the behavior should be consistent regardless of the configuration, hence the tests should not be changed, since it passes the CI (Java 11)

I'll set up the CI to test, package and generate the javadocs for this project in order to replicate what you witnessed, this will help debugging.

**Comment by ed-g** [comment]
Hi @lionel-nj OK I've created separate pull requests for each independent change.

**Comment by lionel-nj** [comment]
Thank you @ed-g :)

**Comment by barbeau** [comment]
Closing this, as it was split into separate PRs:
* https://github.com/MobilityData/gtfs-validator/pull/1090
* https://github.com/MobilityData/gtfs-validator/pull/1091
* https://github.com/MobilityData/gtfs-validator/pull/1092

(thanks @ed-g!)

**Pull request closed without merging**
