### PR TITLE
feat: Make file headers available in CSV table containers

### PR DESCRIPTION
**Pull request by aababilov**
Some validation rules may need to check whether a certain column is
present. E.g., this can allow them to skip further validation.

Unit tests are simplified and mocks are removed.

### CODE REVIEW

**Comment by aababilov** [comment]
Note that JavaDocs do not have the `@return` or `@param` section. This conforms to Google Java style that says that redundant sections are not required if the main comment already explains everything.

**Comment by barbeau** [comment]
>Column names are case-insensitive. Real feeds can capitalize them.

https://gtfs.org/reference/static says under "File Requirements:"

>All field names are case-sensitive.

@MobilityData/transit-specs Thoughts on this?

**Comment by lionel-nj** [comment]
Hi @aababilov Thanks for working on this. I will soon be reviewing :)

**Comment by aababilov** [comment]
> > Column names are case-insensitive. Real feeds can capitalize them.
> 
> https://gtfs.org/reference/static says under "File Requirements:"
> 
> > All field names are case-sensitive.
> 
> @MobilityData/transit-specs Thoughts on this?

Fair point! Let's keep column names case-sensitive. We can revisit that topic later if needed.

I would like to avoid extra discussion for this commit, so let's keep the old behavior.

**Comment by aababilov** [comment]
> Hi @aababilov Thanks for working on this. I will soon be reviewing :)

Merci beaucoup!

**Comment by aababilov** [comment]
Friendly ping 😉

Den tors 15 apr. 2021 07:21Lionel Nébot Janvier ***@***.***>
skrev:

**Review by lionel-nj — APPROVED** [review]
Thanks @aababilov LGTM

**Review by barbeau — APPROVED** [review]
Thanks @aababilov! 👍

**Comment by aababilov** [comment]
Thanks for review!

**Pull request merged**
