### PR TITLE
ci: determine max memory on ci [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by lionel-nj**
**Summary:**

This is a "test" PR to determine  the max memory that can be used on CI used at runtime.
**Expected behavior:** 

No code change: information should be printed

Please make sure these boxes are checked before submitting your pull request - thanks!

~- [ ] Run the unit tests with `gradle test` to make sure you didn't break anything~
- [x] Format the title like "feat: -new feature short description-" (PR title must follow the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/))
~- [ ] Linked all relevant issues~
~- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~

### CODE REVIEW

**Comment by lionel-nj** [comment]
I could not find documentation on a possible memory limit applied in GitHub Action. But, Apparently the maximum memory that can be used on CI (1.6GB) differs from the one that can be used locally (+/- 2GB):

Capture d’écran, le 2020-12-10 à 13 34 01

**Comment by barbeau** [comment]
I'd be inclined to remove the Netherlands / OV dataset from the GitHub CI then to solve the end-to-end issue, as that seems to be the only dataset that can't run on GitHub CI:
https://github.com/MobilityData/gtfs-validator/runs/1532189528#step:8:131

BTW, @lionel-nj could you open an issue for end-to-end builds failing on GitHub so we have a record of that?

**Comment by lionel-nj** [comment]
See https://github.com/MobilityData/gtfs-validator/issues/557

**Comment by lionel-nj** [comment]
> I'd be inclined to remove the Netherlands / OV dataset from the GitHub CI

See https://github.com/MobilityData/gtfs-validator/pull/558/

> BTW, @lionel-nj could you open an issue for end-to-end builds failing on GitHub so we have a record of that?

See #557

**Pull request closed without merging**
